### ISSUE TITLE
As an attendee, I want to be able to chat with the organizer so I can discuss about informations related to the event

### ISSUE THREAD

**Issue by alvitoraidhy** [chingu-voyages/v36-bears-team-20#25]
**__User Story Description__**
As an attendee
I want to be able to chat with the organizer
So I can discuss about informations related to the event

**__Steps to Follow__**
- [x] #26
- [x] #28 
- [x] #29
- [x] #27

**__Additional Considerations__**
[This might be useful.](https://socket.io/get-started/private-messaging-part-1/)

**Comment by elliotwutingfeng** [comment]
### Proposed chat process flow
#### Structure
Each **Event** has 1 **Organizer** and 0 or more **Guests**.

For each **Event**, each **Organizer-Guest** pair will be assigned a unique socket.io **chatroom**, specifically for that **Event**.

Chat history is stored on server and displayed in chat for both **Organizer** and **Guest**.

Both **Organizer** and **Guest** can see each other's in-chat/idle/offline status (i.e. in-chat means whether the person has the chat-window open or not)

#### Scenarios
- When **Guest** joins **Event** for the first time, **Organizer-Guest** chatroom will be created specifically for that **Event**. The **Guest** + **chatroom** will be added to an **Active Guests** list.
- When **Guest** leaves **Event**, the **Guest** + **chatroom** will be moved to a **Withdrawn Guests** list. This list is visible only to **Organizer**. **Organizer** can  access the **chatroom** to view chat history, but cannot talk to **Guest**, since **Guest** has left the **Event**.
- If **Guest** rejoins the **Event**, the **Guest** + **chatroom** will be moved back to  **Active Guests** list from **Withdrawn Guests** list. Both **Organizer** and **Guest** can now continue to talk to each other.

Some mockups
#### Chat Window from Guest Perspective
![ChatApp](https://user-images.githubusercontent.com/30223404/151045703-a73e4aa2-8aae-46e9-85c3-588a94977cfe.png)

#### Chat button on map for user to view all chats, with unread chats counter.
![ChatButtonOnMap](https://user-images.githubusercontent.com/30223404/151045784-6b4472b6-916d-475c-a133-bad55a995f60.png)

I'm thinking of displaying something like this when the user clicks the green chat button on the map.
![1*m9-IZuxS5_GXsMoLvIcVJA](https://user-images.githubusercontent.com/30223404/151046601-2c04e4aa-587a-4342-a8b5-8b4c7335be0d.png)
(photo taken from https://medium.com/carousell-insider/assembling-robust-web-chat-applications-with-javascript-an-in-depth-guide-9f36685fc1bc)

---
For this sprint, we should focus on getting a working chat window up when the user clicks the chat icon on the event popup bubble. The floating green button is just a suggestion by me for now, it will probably change depending on your inputs.
